#https://docs.docker.com/compose/compose-file/
services:
  proxy:
    image: "traefik:latest"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - odds_prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`proxy.odds.localhost`)"
      - "traefik.http.routers.proxy.entrypoints=web"
      - "traefik.http.services.proxy.loadbalancer.server.port=8080"
  frontend:
    image: odds-frontend:latest
    networks:
      - odds_prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.odds.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
  backend:
    image: odds-backend:latest
    environment:
      - CONFIG_PATH=/examples/example2/millennium-falcon.json
    networks:
      - odds_prod
    volumes:
      - ./original/examples:/examples:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.odds.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
networks:
  odds_prod:
    driver: bridge
